### ISSUE TITLE
C2146: syntax error : missing ';' before identifier 'SIZE_T'

### ISSUE THREAD

**Issue by xNarkon** [ReactiioN1337/aero-overlay#1]
Hello,

There is an error in Surface.hpp

Line 13: 
static constexpr size_t MAX_RENDER_ELEMENTS = 512;

C2146: syntax error : missing ';' before identifier 'size_t'
C4430: missing type specifier - int assumed. Note: C++ does not support default-int

Building with QT creator -> compiler MSVC 2013 32bit

What's is wrong, I just cant solve it alone 😄

**Comment by ReactiioN1337** [comment]
The problem is MSVC 2013. Remove the constexpr and recompile it.
BTW: who's using MSVC2013 in 2017?
