### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by lofcz** [ReactiioN1337/aero-overlay#4]
Hey ReactiioN1337,

thanks for this awesome library. Before stumbling upon this I've used GDI for my external overlay and even after implementing double buffering it flickered. Including aero into my project and replacing GDI with it was a real ease (somewhere about 30mins - 1hr) due to the well written readme. 

![image](https://user-images.githubusercontent.com/10260230/87366790-d3011680-c579-11ea-8a8d-e0325217d8df.png)

**Comment by ReactiioN1337** [comment]
Thank you for those kind words, I really appreciate them.
