### ISSUE TITLE
Fullscreen handling?

### ISSUE THREAD

**Issue by nuuSolutions** [ReactiioN1337/aero-overlay#5]
Overlay does not show up when the game (unreal engine 4) switches to fullscreen.
What am I doing wrong?
Somtetimes it seems to work (e.g. when two screens are active)
Starting the thread differently also helped, but then I got tearing in the game.

Any hints on how to do it right fullscreen?

**Comment by ReactiioN1337** [comment]
You're doing nothing wrong. Might has something to do with window flags, so maybe check other applications which are working in fullscreen and with topmost (such as GeForce Experience Overlay).

**Comment by nuuSolutions** [comment]
Waited the whole year for this :((
